# This workflow will install Python dependencies, run tests, generate coverage
# report and upload it to codecov.
# For more information, see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests with coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies and ruptures[dev]
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test]
        python -c "import pytest_cov"
    - name: Test with pytest
      run: |
        python -m pytest
    - name: Upload to Codecov
      run: |
        bash <(curl -s https://codecov.io/bash)
    - uses: actions/upload-artifact@v2
      with:
        path: coverage.xml
